@startuml
title "Copy Aubie" Domain Model
class Player {
play
}

class Sequence {
speed
length
}

class Button {
location
tone
color
}


Player "1" -- "1" Sequence : view and repeat >
Sequence "1" *-- "1...*" Button : consists of >

@enduml